apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: heavenly-ingress
  namespace: heavenly
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-next-upstream: "error timeout http_502 http_503 http_504"
spec:
  ingressClassName: nginx
  rules:
    - host: heavenly.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bff-service
                port:
                  number: 8080
